"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./os.module.css";

type View='today'|'timeline'|'events'|'groups'|'outreach'|'quality';
async function api(action:string,payload:any={}){const r=await fetch('/api/os',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Request failed');return d.data}
const first=(n='')=>n.split(' ')[0]||'there';

export default function NetworkOS(){
 const[view,setView]=useState<View>('today'),[dash,setDash]=useState<any>(null),[groups,setGroups]=useState<any[]>([]),[dupes,setDupes]=useState<any[]>([]),[timeline,setTimeline]=useState<any>(null),[notice,setNotice]=useState('Loading Network OS…'),[busy,setBusy]=useState(false);
 const[eventName,setEventName]=useState(''),[eventTopic,setEventTopic]=useState('poker'),[eventDate,setEventDate]=useState(''),[candidates,setCandidates]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]);
 const[groupName,setGroupName]=useState(''),[groupTopic,setGroupTopic]=useState(''),[groupAffinity,setGroupAffinity]=useState('70'),[groupFollowers,setGroupFollowers]=useState('0'),[groupInactive,setGroupInactive]=useState('');
 async function refresh(){const d=await api('dashboard');setDash(d);setNotice('');}
 useEffect(()=>{refresh().catch(e=>setNotice(e.message))},[]);
 async function loadView(v:View){setView(v);try{if(v==='groups')setGroups(await api('groups'));if(v==='quality')setDupes(await api('duplicates'))}catch(e:any){setNotice(e.message)}}
 async function openTimeline(id:string){setBusy(true);try{setTimeline(await api('timeline',{person_id:id}));setView('timeline')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function buildCandidates(){setBusy(true);try{const d=await api('event_candidates',{topic:eventTopic,limit:40});setCandidates(d);setSelected(d.filter((x:any)=>x.fit>=65).map((x:any)=>x.id));setNotice(`Ranked ${d.length} people for ${eventTopic}`)}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function createEvent(){if(!eventName.trim())return setNotice('Give the event a name first');setBusy(true);try{await api('create_event',{name:eventName,topic:eventTopic,event_date:eventDate||null,candidates:candidates.filter(x=>selected.includes(x.id)).map(x=>({person_id:x.id,fit:x.fit,reasons:x.reasons}))});setNotice(`Created ${eventName} with ${selected.length} candidates`);setCandidates([]);setSelected([]);await refresh()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function saveGroup(){if(!groupName.trim())return;setBusy(true);try{await api('save_group',{name:groupName,rules:{topic:groupTopic||undefined,topic_min:groupTopic?60:undefined,affinity_min:Number(groupAffinity)||0,followers_min:Number(groupFollowers)||0,inactive_days:Number(groupInactive)||undefined}});setGroups(await api('groups'));setGroupName('');setNotice('Dynamic group saved') }catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function draft(person_id:string,event_id?:string){setBusy(true);try{const d=await api('outreach',{action:'draft',person_id,event_id,channel:'dm'});await navigator.clipboard.writeText(d.message);setNotice(`Draft copied for ${first(dash?.recommendations?.find((x:any)=>x.id===person_id)?.name)}`);await refresh()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function merge(keep_id:string,remove_id:string){if(!confirm('Merge these records? Notes, events and outreach will move to the kept record.'))return;setBusy(true);try{await api('merge_people',{keep_id,remove_id});setDupes(await api('duplicates'));setNotice('Duplicate merged')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 const nav:[View,string][]=[['today','Today'],['timeline','Timeline'],['events','Invite Builder'],['groups','Smart Groups'],['outreach','Outreach'],['quality','Data Quality']];
 return <main className={styles.shell}>
  <header className={styles.header}><div><small>PRIVATE NETWORK OS · V1</small><h1>Network</h1></div><a href="/">Classic CRM</a></header>
  <nav className={styles.nav}>{nav.map(([k,l])=><button key={k} onClick={()=>loadView(k)} className={view===k?styles.active:''}>{l}</button>)}</nav>
  {notice&&<div className={styles.notice}>{notice}</div>}
  {busy&&<div className={styles.progress}>Working…</div>}

  {view==='today'&&<section>
   <div className={styles.hero}><div><small>SMART “WHO SHOULD I CONTACT?”</small><h2>Your network, prioritized.</h2><p>People worth reaching out to now, ranked by relationship value and time since contact.</p></div><div className={styles.metrics}><b>{dash?.counts?.people||0}<span>people</span></b><b>{dash?.counts?.events||0}<span>events</span></b><b>{dash?.counts?.drafts||0}<span>drafts</span></b></div></div>
   <div className={styles.grid}>{(dash?.recommendations||[]).map((p:any,i:number)=><article className={styles.card} key={p.id}><span className={styles.rank}>{i+1}</span><h3>{p.name}</h3><p>{[p.role,p.company].filter(Boolean).join(' · ')||p.summary||'No context yet'}</p><div className={styles.score}><b>{p.priority}</b><span>priority</span></div><ul>{p.reasons.map((r:string)=><li key={r}>{r}</li>)}</ul><div className={styles.actions}><button onClick={()=>openTimeline(p.id)}>Timeline</button><button onClick={()=>draft(p.id)}>Draft DM</button></div></article>)}</div>
  </section>}

  {view==='timeline'&&<section><div className={styles.sectionHead}><div><small>RELATIONSHIP TIMELINE</small><h2>{timeline?.person?.name||'Choose someone from Today'}</h2></div></div>{timeline&&<div className={styles.twoCol}><div><h3>Known facts</h3><div className={styles.chips}>{(timeline.facts||[]).map((f:any)=><span key={f.id}>{f.fact_type}: {f.fact_value} · {f.confidence}%</span>)}</div></div><div className={styles.timeline}>{timeline.items.map((x:any,i:number)=><article key={i}><time>{new Date(x.date).toLocaleDateString()}</time><div><b>{x.title}</b><p>{x.detail}</p></div></article>)}</div></div>}</section>}

  {view==='events'&&<section><div className={styles.sectionHead}><div><small>EVENT INVITE BUILDER</small><h2>Build a room with intention.</h2></div></div><div className={styles.formRow}><input placeholder="Event name" value={eventName} onChange={e=>setEventName(e.target.value)}/><input placeholder="Topic" value={eventTopic} onChange={e=>setEventTopic(e.target.value)}/><input type="datetime-local" value={eventDate} onChange={e=>setEventDate(e.target.value)}/><button onClick={buildCandidates}>Rank candidates</button></div>{candidates.length>0&&<><div className={styles.toolbar}><b>{selected.length} selected</b><button onClick={createEvent}>Create event shortlist</button></div><div className={styles.list}>{candidates.map((p:any)=><label key={p.id} className={styles.personRow}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}/><span><b>{p.name}</b><small>{[p.role,p.company].filter(Boolean).join(' · ')}</small></span><em>{p.reasons.join(' · ')}</em><strong>{p.fit}</strong></label>)}</div></>}</section>}

  {view==='groups'&&<section><div className={styles.sectionHead}><div><small>DYNAMIC GROUPS</small><h2>Lists that update themselves.</h2></div></div><div className={styles.formRow}><input placeholder="Group name" value={groupName} onChange={e=>setGroupName(e.target.value)}/><input placeholder="Topic (optional)" value={groupTopic} onChange={e=>setGroupTopic(e.target.value)}/><input placeholder="Min affinity" value={groupAffinity} onChange={e=>setGroupAffinity(e.target.value)}/><input placeholder="Min followers" value={groupFollowers} onChange={e=>setGroupFollowers(e.target.value)}/><input placeholder="Inactive days" value={groupInactive} onChange={e=>setGroupInactive(e.target.value)}/><button onClick={saveGroup}>Save group</button></div><div className={styles.grid}>{groups.map(g=><article className={styles.card} key={g.id}><h3>{g.name}</h3><p>{g.description||Object.entries(g.rules).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p><div className={styles.score}><b>{g.member_count}</b><span>members</span></div><div className={styles.chips}>{g.members.slice(0,8).map((p:any)=><span key={p.id}>{p.name}</span>)}</div></article>)}</div></section>}

  {view==='outreach'&&<section><div className={styles.sectionHead}><div><small>OUTREACH WORKSPACE</small><h2>Personalized, trackable communication.</h2></div></div><div className={styles.twoCol}><div><h3>Recent drafts</h3>{(dash?.outreach||[]).map((o:any)=><article className={styles.message} key={o.id}><b>{o.channel.toUpperCase()} · {o.status}</b><p>{o.message}</p><button onClick={()=>navigator.clipboard.writeText(o.message)}>Copy</button></article>)}</div><div><h3>Upcoming events</h3>{(dash?.events||[]).map((e:any)=><article className={styles.message} key={e.id}><b>{e.name}</b><p>{e.topic}{e.event_date?` · ${new Date(e.event_date).toLocaleString()}`:''}</p></article>)}</div></div></section>}

  {view==='quality'&&<section><div className={styles.sectionHead}><div><small>DUPLICATE DETECTION</small><h2>Keep the network clean.</h2></div></div>{dupes.length===0?<div className={styles.empty}>No likely duplicates found.</div>:<div className={styles.list}>{dupes.map((d:any,i:number)=><article className={styles.dup} key={i}><div><b>{d.a.name}</b><small>{d.a.email||d.a.phone||d.a.instagram}</small></div><strong>{d.score}%</strong><div><b>{d.b.name}</b><small>{d.b.email||d.b.phone||d.b.instagram}</small></div><em>{d.reasons.join(' · ')}</em><button onClick={()=>merge(d.a.id,d.b.id)}>Keep first, merge second</button></article>)}</div>}</section>}
 </main>
}
