"use client";
import {useEffect,useMemo,useState} from "react";

type Tab="home"|"remember"|"search"|"people"|"lists"|"import"|"status";
type Sort="best"|"affinity"|"name";
type Filter="all"|"founders"|"poker"|"werewolf"|"creators"|"large_ig"|"reachable"|"high_affinity";
type Person={person_id:string;name?:string;phone?:string;email?:string;instagram?:string;instagram_followers?:number;summary?:string;company?:string;role?:string;affinity_score?:number};
type Interest={topic:string;strength:number};
type Item={person:Person;score?:number;affinity_score?:number;relationship_score?:number;interests:Interest[];memories_count:number;connections_count:number;last_memory?:{raw_note?:string}|null};
type Stats={people:number;memories:number;interests:number;connections:number;missing_instagram:number;average_affinity_score?:number};
type Profile=Item&{memories:Array<{memory_id:string;raw_note?:string;date?:string}>;connections:Array<{connection_id:string;relationship?:string;other_person?:Person}>};

async function crm(action:string,payload:Record<string,unknown>={}){const r=await fetch('/api/crm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Request failed');return d.data}
const affinity=(x:Item|Profile)=>Number(x.affinity_score??x.person.affinity_score??x.relationship_score??0);
const strength=(n:number)=>Math.round(Math.max(0,Math.min(5,n))/5*100);
const handle=(v?:string)=>String(v||'').replace(/^@/,'');
const compact=(n?:number)=>!n?'':n>=1000000?`${(n/1000000).toFixed(n>=10000000?0:1)}M`:n>=1000?`${(n/1000).toFixed(n>=100000?0:1)}K`:String(n);
function copy(v?:string){if(v)navigator.clipboard.writeText(v)}
function searchable(item:Item){const p=item.person;return [p.name,p.role,p.company,p.instagram,p.phone,p.email,p.summary,item.last_memory?.raw_note,item.interests.map(i=>i.topic).join(' ')].filter(Boolean).join(' ').toLowerCase()}
function localScore(item:Item,terms:string[]){const p=item.person,name=String(p.name||'').toLowerCase(),role=String(p.role||'').toLowerCase(),company=String(p.company||'').toLowerCase(),topics=item.interests.map(i=>String(i.topic||'').toLowerCase()),text=searchable(item);let score=0;for(const term of terms){if(name===term)score+=100;else if(name.includes(term))score+=45;if(role.includes(term))score+=30;if(company.includes(term))score+=20;if(topics.some(t=>t===term))score+=45;else if(topics.some(t=>t.includes(term)))score+=30;if(text.includes(term))score+=10}return score+affinity(item)*.05}
function matchesFilter(item:Item,filter:Filter){const text=searchable(item),p=item.person;if(filter==='all')return true;if(filter==='founders')return /founder|co-founder|entrepreneur/.test(text);if(filter==='poker')return text.includes('poker');if(filter==='werewolf')return text.includes('werewolf');if(filter==='creators')return /creator|influencer|youtube|tiktok|content/.test(text);if(filter==='large_ig')return Number(p.instagram_followers||0)>=10000;if(filter==='reachable')return Boolean(p.phone);if(filter==='high_affinity')return affinity(item)>=70;return true}
function affinityReasons(item:Item){const out:string[]=[];const text=searchable(item);if(affinity(item)>=70)out.push('High recorded affinity');if(/founder|creator|organizer|sponsor|partner/.test(text))out.push('Role aligns with your network');if(item.interests.some(i=>i.strength>=4))out.push('Strong shared interests');if(item.connections_count>=3)out.push('Well connected');if(Number(item.person.instagram_followers||0)>=10000)out.push('Meaningful audience reach');if(item.memories_count>=3)out.push('Well documented relationship');return out.length?out:['Not enough evidence yet']}

function ContactRow({item,rank,onOpen,selected,onToggle}:{item:Item;rank:number;onOpen:(id:string)=>void;selected:boolean;onToggle:(id:string)=>void}){
 const p=item.person,top=item.interests.slice(0,3);
 return <article className={`contactRow ${selected?'selected':''}`}>
  <button className="selectBox" aria-label={`Select ${p.name||'person'}`} onClick={()=>onToggle(p.person_id)}>{selected?'✓':''}</button>
  <button className="rowMain" onClick={()=>onOpen(p.person_id)}>
   <span className="rank">{rank}</span><span className="identity"><strong>{p.name||'Unknown'}</strong><small>{[p.role,p.company].filter(Boolean).join(' · ')||p.summary||'No details yet'}</small></span>
   <span className="interestLine">{top.map(i=><em key={i.topic}>{i.topic} {strength(i.strength)}</em>)}</span>
   <span className="affinity"><strong>{affinity(item)}</strong><small>affinity</small></span>
  </button>
  <div className="reach">
   {p.phone&&<><a href={`sms:${p.phone}`}>{p.phone}</a><button onClick={()=>copy(p.phone)}>Copy</button></>}
   {p.instagram&&<><a className="instagram" href={`https://instagram.com/${handle(p.instagram)}`} target="_blank" rel="noreferrer">@{handle(p.instagram)}{Number(p.instagram_followers)>=10000&&<b> · {compact(p.instagram_followers)}</b>}</a><button onClick={()=>copy(p.instagram)}>Copy</button></>}
  </div>
 </article>
}

export default function Home(){
 const[tab,setTab]=useState<Tab>('home'),[query,setQuery]=useState(''),[note,setNote]=useState(''),[bulk,setBulk]=useState(''),[sort,setSort]=useState<Sort>('best'),[filter,setFilter]=useState<Filter>('all'),[people,setPeople]=useState<Item[]>([]),[results,setResults]=useState<Item[]>([]),[stats,setStats]=useState<Stats|null>(null),[profile,setProfile]=useState<Profile|null>(null),[lists,setLists]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[smartBusy,setSmartBusy]=useState(false);
 async function refresh(){const[s,p]=await Promise.all([crm('stats'),crm('list_people',{limit:500})]);setStats(s);setPeople(p||[]);try{setLists(await crm('list_lists')||[])}catch{setLists([])}}
 useEffect(()=>{refresh().catch(e=>setStatus(e.message))},[]);
 useEffect(()=>{setResults([])},[query]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase(),terms=q.split(/\s+/).filter(Boolean);let rows=(tab==='search'&&results.length?results:people).filter(x=>matchesFilter(x,filter));if((tab==='search'||tab==='people')&&terms.length)rows=rows.filter(x=>terms.every(term=>searchable(x).includes(term)));rows=rows.slice();if(sort==='affinity')rows.sort((a,b)=>affinity(b)-affinity(a));else if(sort==='name')rows.sort((a,b)=>String(a.person.name||'').localeCompare(String(b.person.name||'')));else if(tab==='search'&&terms.length)rows.sort((a,b)=>localScore(b,terms)-localScore(a,terms));else rows.sort((a,b)=>affinity(b)-affinity(a)||b.memories_count-a.memories_count);return rows},[people,results,query,sort,tab,filter]);
 const selectedPeople=useMemo(()=>people.filter(x=>selected.includes(x.person.person_id)),[people,selected]);
 async function smartSearch(){if(!query.trim())return;setSmartBusy(true);setStatus('');try{const d:any[]=await crm('search_network',{query,limit:100});setResults((d||[]).map(r=>({...r,interests:r.interests||[],memories_count:r.matching_memories?.length||0,connections_count:0,last_memory:r.matching_memories?.[0]||null})))}catch(e){setStatus(e instanceof Error?e.message:'Smart search failed')}finally{setSmartBusy(false)}}
 async function remember(){if(!note.trim())return;setBusy(true);try{const d=await crm('capture_note',{text:note,source:'web'});setStatus(`Saved to ${d.person?.name||'person'} ✓`);setNote('');await refresh()}catch(e){setStatus(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 async function importLines(){const lines=bulk.split('\n').map(x=>x.trim()).filter(Boolean);if(!lines.length)return;setBusy(true);try{await crm('bulk_capture',{lines});setBulk('');await refresh();setStatus(`Imported ${lines.length} entries ✓`)}finally{setBusy(false)}}
 async function openProfile(id:string){setProfile(await crm('get_person',{person_id:id}))}
 async function setAffinity(){if(!profile)return;const raw=prompt('Affinity score 0–100',String(affinity(profile)));if(raw===null)return;const value=Math.max(0,Math.min(100,Number(raw)));if(Number.isNaN(value))return;await crm('set_affinity',{person_id:profile.person.person_id,affinity_score:value});await openProfile(profile.person.person_id);await refresh()}
 async function editContact(){if(!profile)return;const phone=prompt('Phone number',profile.person.phone||'');if(phone===null)return;const instagram=prompt('Instagram handle',profile.person.instagram||'');if(instagram===null)return;const email=prompt('Email',profile.person.email||'');if(email===null)return;await crm('quick_add',{person_id:profile.person.person_id,kind:'contact',phone,instagram,email});await openProfile(profile.person.person_id);await refresh();setStatus('Contact updated ✓')}
 function toggleSelected(id:string){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}
 function selectVisible(){setSelected(current=>Array.from(new Set([...current,...visible.map(x=>x.person.person_id)])))}
 function copySelectedPhones(){const phones=selectedPeople.map(x=>x.person.phone).filter(Boolean).join('\n');if(!phones){setStatus('No selected phone numbers');return}copy(phones);setStatus(`Copied ${selectedPeople.filter(x=>x.person.phone).length} phone numbers ✓`)}
 async function createListFromSelection(){if(!selected.length)return;const name=prompt('List name, e.g. Founder Poker Night');if(!name)return;const topic=prompt('Topic, e.g. poker')||'';setBusy(true);try{const list=await crm('create_list',{name,topic});await Promise.all(selected.map(person_id=>crm('add_to_list',{list_id:list.list_id,person_id,status:'candidate'})));setSelected([]);await refresh();setTab('lists');setStatus(`Created ${name} with ${selected.length} candidates ✓`)}catch(e){setStatus(e instanceof Error?e.message:'Could not create list')}finally{setBusy(false)}}
 const nav=(t:Tab,label:string)=><button className={tab===t?'active':''} onClick={()=>{setTab(t);setQuery('');setResults([]);setStatus('')}}>{label}</button>;
 const filterBar=<div className="filterBar">{([['all','All'],['founders','Founders'],['poker','Poker'],['werewolf','Werewolf'],['creators','Creators'],['large_ig','Large Instagram'],['reachable','Has phone'],['high_affinity','High affinity']] as Array<[Filter,string]>).map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div>;
 const list=(items:Item[])=><section className="contactList">{items.map((x,i)=><ContactRow key={x.person.person_id} item={x} rank={i+1} onOpen={openProfile} selected={selected.includes(x.person.person_id)} onToggle={toggleSelected}/>)}</section>;
 return <main className="shell">
  <header className="header"><div><p className="eyebrow">PRIVATE NETWORK OS · V0.5</p><h1>Network</h1></div><nav>{nav('home','Home')}{nav('remember','Remember')}{nav('search','Search')}{nav('people','People')}{nav('lists','Lists')}{nav('import','Import')}{nav('status','Status')}</nav></header>
  {status&&<p className="status">{status}</p>}
  {selected.length>0&&<section className="selectionBar"><strong>{selected.length} selected</strong><button onClick={selectVisible}>Select visible</button><button onClick={copySelectedPhones}>Copy phones</button><button className="primary" disabled={busy} onClick={createListFromSelection}>Create invite list</button><button onClick={()=>setSelected([])}>Clear</button></section>}
  {tab==='home'&&<><section className="heroBanner"><strong>{stats?.people||0}</strong><div><h2>People in your network</h2><p>{stats?.memories||0} memories · {stats?.interests||0} interests · {stats?.connections||0} connections</p></div></section><div className="sectionHead"><h2>Best candidates</h2><button onClick={()=>setTab('people')}>View all</button></div>{list(people.slice(0,12))}</>}
  {tab==='remember'&&<section className="card remember"><h2>What should I remember?</h2><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Sharon is a founder, loves poker, @sharon with 120k Instagram followers…"/><button className="primary" disabled={!note.trim()||busy} onClick={remember}>{busy?'Saving…':'Remember'}</button></section>}
  {tab==='search'&&<><section className="searchBar"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')smartSearch()}} placeholder="Type poker for instant search"/><select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="best">Best match</option><option value="affinity">Affinity</option><option value="name">Name</option></select><button className="primary" disabled={!query.trim()||smartBusy} onClick={smartSearch}>{smartBusy?'Searching…':'Smart Search'}</button></section>{filterBar}<div className="resultLine"><p>{query?`${visible.length} instant matches${results.length?' · smart-ranked':''}`:'Search instantly. Use Smart Search only for complex requests.'}</p><button onClick={selectVisible}>Select all results</button></div>{list(visible)}</>}
  {tab==='people'&&<><section className="searchBar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter contacts instantly"/><select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="best">Best candidates</option><option value="affinity">Affinity</option><option value="name">Name</option></select></section>{filterBar}<div className="resultLine"><p>{visible.length} people</p><button onClick={selectVisible}>Select visible</button></div>{list(visible)}</>}
  {tab==='lists'&&<><div className="sectionHead"><h2>Invite lists</h2><button onClick={()=>setTab('search')}>Find candidates</button></div>{lists.length?lists.map(l=><article className="card mini" key={l.list_id}><div><strong>{l.name}</strong><span>{l.topic||'General'}</span></div><b>{l.member_count} candidates</b></article>):<section className="card"><p>No lists yet, or the latest Apps Script has not been deployed.</p><button className="primary" onClick={()=>setTab('search')}>Build your first list</button></section>}</>}
  {tab==='import'&&<section className="card remember"><h2>Bulk import</h2><textarea value={bulk} onChange={e=>setBulk(e.target.value)} placeholder="One person per line"/><button className="primary" disabled={!bulk.trim()||busy} onClick={importLines}>Import</button></section>}
  {tab==='status'&&<section className="card"><h2>Deployment</h2><p>Frontend deploys automatically from main. Apps Script still requires copying Code.gs and deploying a new version.</p></section>}
  {profile&&<div className="modalBackdrop" onClick={()=>setProfile(null)}><section className="profileModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setProfile(null)}>×</button><div className="profileTop"><div><h2>{profile.person.name}</h2><p>{[profile.person.role,profile.person.company].filter(Boolean).join(' · ')}</p></div><button className="affinityEdit" onClick={setAffinity}><strong>{affinity(profile)}</strong><span>Affinity · edit</span></button></div><div className="profileActions"><button onClick={editContact}>Edit contact</button><button onClick={()=>toggleSelected(profile.person.person_id)}>{selected.includes(profile.person.person_id)?'Remove from shortlist':'Add to shortlist'}</button></div><div className="profileReach">{profile.person.phone&&<><a href={`sms:${profile.person.phone}`}>{profile.person.phone}</a><button onClick={()=>copy(profile.person.phone)}>Copy</button></>}{profile.person.instagram&&<><a className="instagram" href={`https://instagram.com/${handle(profile.person.instagram)}`} target="_blank" rel="noreferrer">@{handle(profile.person.instagram)}{Number(profile.person.instagram_followers)>=10000&&` · ${compact(profile.person.instagram_followers)} followers`}</a><button onClick={()=>copy(profile.person.instagram)}>Copy</button></>}</div><div className="chips">{profile.interests.map(i=><span key={i.topic}>{i.topic} {strength(i.strength)}</span>)}</div><section className="affinityWhy"><h3>Why this affinity</h3>{affinityReasons(profile).map(reason=><p key={reason}>• {reason}</p>)}</section><h3>Story</h3>{profile.memories.map(m=><article className="memory" key={m.memory_id}><small>{m.date?new Date(m.date).toLocaleDateString():''}</small><p>{m.raw_note}</p></article>)}</section></div>}
 </main>
}
