import { randomUUID } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabase/admin";

type Payload = Record<string, any>;
type DbError = { message?: string; details?: string; hint?: string; code?: string };
const clamp=(v:unknown)=>Math.max(0,Math.min(100,Math.round(Number(v)||0)));
const clean=(v:unknown)=>String(v??"").trim();
const norm=(v:unknown)=>clean(v).toLowerCase().replace(/[’]/g,"'");
const id=(p:string)=>`${p}_${randomUUID()}`;
const aliases:Record<string,string[]>={poker:["poker","holdem","hold'em","texas hold"],werewolf:["werewolf","mafia game"],games:["game night","board game","boardgame"],creator:["creator","content creator","influencer","youtube","tiktok"],founder:["founder","cofounder","co-founder","entrepreneur","startup"],community:["community builder","organizer","host"],marketing:["marketing","growth","brand strategy"],film:["film","filmmaker","cinema","movie"],chess:["chess"],volleyball:["volleyball"]};

function message(error:unknown){if(error instanceof Error)return error.message;if(error&&typeof error==="object"){const e=error as DbError;return [e.message,e.details,e.hint,e.code?`Code: ${e.code}`:""].filter(Boolean).join(" · ")||JSON.stringify(error)}return String(error||"Unknown server error")}
function fail(stage:string,error:unknown):never{throw new Error(`${stage}: ${message(error)}`)}
function topicFrom(text:string){const value=norm(text);for(const [topic,words] of Object.entries(aliases))if(words.some(word=>value.includes(word)))return topic;return ""}
function nameFrom(text:string){const first=text.split(/[,.!?;\n]/)[0].trim(),cue=first.search(/\b(loves?|likes?|hates?|enjoys?|plays?|hosts?|is|works?|met|wants?)\b/i),candidate=(cue>0?first.slice(0,cue):first).trim();return /^[A-Za-z][A-Za-z'.-]*(?:\s+[A-Za-z][A-Za-z'.-]*){0,3}$/.test(candidate)?candidate:"Unknown"}
function evidenceFor(text:string){const t=norm(text),negative=/\b(hates?|dislikes?|doesn't like|does not like|not interested|no longer|used to)\b/.test(t);let enthusiasm=28,behavior=15,specificity=45,certainty=82,evidence_type="mention";if(/obsessed|favorite|passion|absolutely loves|lives for/.test(t)){enthusiasm=98;evidence_type="direct_preference"}else if(/\bloves?\b|huge fan|very into/.test(t)){enthusiasm=92;evidence_type="direct_preference"}else if(/really likes|really enjoys|very interested/.test(t)){enthusiasm=82;evidence_type="direct_preference"}else if(/\blikes?\b|\benjoys?\b/.test(t)){enthusiasm=70;evidence_type="stated_interest"}else if(/interested|wants to learn|wants to try/.test(t)){enthusiasm=52;evidence_type="curiosity"}if(/hosts?|plays every|weekly|every week|tournament|competes|teaches/.test(t)){behavior=96;specificity=92;evidence_type="demonstrated_behavior"}else if(/regularly|plays often|attended multiple|comes to every/.test(t)){behavior=84;specificity=82}else if(/played|attended|joined|participated/.test(t)){behavior=62;specificity=70}if(/maybe|might|possibly|i think|probably|seems/.test(t))certainty=50;let score=clamp(enthusiasm*.52+behavior*.24+specificity*.12+certainty*.12);if(evidence_type==="direct_preference")score=Math.max(score,90);if(enthusiasm>=98)score=Math.max(score,96);if(behavior>=90)score=Math.max(score,95);if(negative)score=Math.min(score,15);return{score,confidence:clamp(certainty*.65+specificity*.2+Math.max(enthusiasm,behavior)*.15),enthusiasm,behavior,specificity,certainty,polarity:negative?-1:1,evidence_type}}
function affinityFor(person:any,count:number){const text=norm(`${person.summary||""} ${person.importance_reason||""}`);let closeness=28,enthusiasm=35;if(/best friend|closest friend|family to me|trust completely/.test(text))closeness=96;else if(/close friend|good friend|really trust|must invite/.test(text))closeness=84;else if(/friend|great person|strong relationship/.test(text))closeness=66;if(/incredible person|one of my favorite|absolutely amazing/.test(text))enthusiasm=95;else if(/amazing|really like|great energy|love working with/.test(text))enthusiasm=80;const interaction=Math.min(100,20+count*15),strategic=Math.min(100,(Number(person.importance)||0)*15+(Number(person.instagram_followers)>=10000?20:0));return{score:clamp(closeness*.35+enthusiasm*.25+interaction*.25+strategic*.15),confidence:clamp(35+count*12),reasons:[closeness>=80?"Strong closeness language":"",enthusiasm>=80?"Strong positive enthusiasm":"",count>=3?"Repeated relationship evidence":""].filter(Boolean)}}
function shape(p:any,topics:any[]=[],memoryCount=0,lastMemory:any=null,connections=0){const affinity=p.affinity_override??p.computed_affinity??0,interests=topics.map(t=>({topic:t.topic,score:t.score,strength:t.score/20,confidence:t.confidence,evidence:Array.isArray(t.explanation)?t.explanation:[]}));return{person:{person_id:p.id,name:p.name,phone:p.phone,email:p.email,instagram:p.instagram,instagram_followers:p.instagram_followers,company:p.company,role:p.role,where_met:p.where_met,summary:p.summary,last_contact:p.last_contact,affinity_override:p.affinity_override,affinity_score:affinity},affinity_score:affinity,computed_affinity:p.computed_affinity,affinity_confidence:p.affinity_confidence,affinity_reasons:p.affinity_reasons||[],relationship_score:affinity,interests,topic_scores:interests,memories_count:memoryCount,connections_count:connections,last_memory:lastMemory}}

async function listPeople(p:Payload){const db=getSupabaseAdmin(),people=await db.from("people").select("*").order("computed_affinity",{ascending:false}).limit(Math.min(Number(p.limit)||500,500));if(people.error)fail("Loading people",people.error);const ids=(people.data||[]).map(x=>x.id),topics=ids.length?await db.from("topic_scores").select("*").in("person_id",ids):{data:[],error:null},memories=ids.length?await db.from("memories").select("id,person_id,raw_note,created_at").in("person_id",ids).order("created_at",{ascending:false}):{data:[],error:null};if(topics.error)fail("Loading topic scores",topics.error);if(memories.error)fail("Loading memories",memories.error);const byTopic=new Map<string,any[]>(),byMem=new Map<string,any[]>();for(const t of topics.data||[])byTopic.set(t.person_id,[...(byTopic.get(t.person_id)||[]),t]);for(const m of memories.data||[])byMem.set(m.person_id,[...(byMem.get(m.person_id)||[]),m]);return(people.data||[]).map(x=>shape(x,byTopic.get(x.id)||[],(byMem.get(x.id)||[]).length,(byMem.get(x.id)||[])[0]||null))}
async function searchNetwork(p:Payload){const db=getSupabaseAdmin(),query=clean(p.query),topic=clean(p.topic)||topicFrom(query),r=await db.rpc("search_people",{search_topic:topic||null,search_text:query||null,result_limit:Number(p.limit)||100});if(r.error)fail("Searching people",r.error);return(r.data||[]).map((x:any)=>({score:clamp((x.topic_score||0)*.8+(x.computed_affinity||0)*.2),topic,topic_fit:x.topic_score||0,topic_fit_score:x.topic_score||0,topic_confidence:x.topic_confidence||0,person:{person_id:x.id,name:x.name,phone:x.phone,email:x.email,instagram:x.instagram,instagram_followers:x.instagram_followers,company:x.company,role:x.role,summary:x.summary},affinity_score:x.computed_affinity||0,computed_affinity:x.computed_affinity||0,interests:x.topic_score?[{topic,score:x.topic_score,strength:x.topic_score/20,confidence:x.topic_confidence}]:[],memories_count:0,connections_count:0}))}
async function getPerson(p:Payload){const db=getSupabaseAdmin(),person=await db.from("people").select("*").eq("id",p.person_id).single();if(person.error)fail("Loading person",person.error);const memories=await db.from("memories").select("*").eq("person_id",person.data.id).order("created_at",{ascending:false}),topics=await db.from("topic_scores").select("*").eq("person_id",person.data.id).order("score",{ascending:false}),connections=await db.from("connections").select("*").or(`person_a_id.eq.${person.data.id},person_b_id.eq.${person.data.id}`);if(memories.error)fail("Loading person memories",memories.error);if(topics.error)fail("Loading person topics",topics.error);if(connections.error)fail("Loading person connections",connections.error);return{...shape(person.data,topics.data||[],memories.data?.length||0,memories.data?.[0]||null,connections.data?.length||0),memories:(memories.data||[]).map(m=>({memory_id:m.id,raw_note:m.raw_note,date:m.created_at})),connections:connections.data||[]}}
async function captureNote(p:Payload){const db=getSupabaseAdmin(),text=clean(p.text||p.raw_note);if(!text)throw new Error("Text required");const name=nameFrom(text),topic=topicFrom(text),lookup=await db.from("people").select("*").ilike("name",name).maybeSingle();if(lookup.error)fail("Finding person",lookup.error);let person=lookup.data;if(!person){const created=await db.from("people").insert({id:id("person"),name,summary:text,last_contact:new Date().toISOString()}).select().single();if(created.error)fail("Creating person",created.error);person=created.data}else{const updated=await db.from("people").update({summary:text,last_contact:new Date().toISOString()}).eq("id",person.id).select().single();if(updated.error)fail("Updating person",updated.error);person=updated.data}const memory={id:id("memory"),person_id:person.id,raw_note:text,topics:topic?[topic]:[],source:p.source||"web"},savedMemory=await db.from("memories").insert(memory).select().single();if(savedMemory.error)fail("Saving memory",savedMemory.error);if(topic){const savedEvidence=await db.from("interest_evidence").insert({id:id("ev"),person_id:person.id,memory_id:memory.id,topic,quote:text,...evidenceFor(text)});if(savedEvidence.error)fail("Saving interest evidence",savedEvidence.error);const all=await db.from("interest_evidence").select("score,confidence,quote,evidence_type").eq("person_id",person.id).eq("topic",topic);if(all.error)fail("Reading interest evidence",all.error);const rows=all.data||[],best=Math.max(...rows.map(x=>Number(x.score)||0),0),avg=rows.reduce((s,x)=>s+Number(x.score||0),0)/Math.max(rows.length,1),score=clamp(best*.75+avg*.25+Math.min(6,Math.max(0,rows.length-1)*2)),upsert=await db.from("topic_scores").upsert({person_id:person.id,topic,score,confidence:clamp(rows.reduce((s,x)=>s+Number(x.confidence||0),0)/Math.max(rows.length,1)),evidence_count:rows.length,explanation:rows.sort((a,b)=>Number(b.score)-Number(a.score)).slice(0,4).map(x=>x.quote)},{onConflict:"person_id,topic"});if(upsert.error)fail("Updating topic score",upsert.error)}const count=await db.from("memories").select("id",{count:"exact",head:true}).eq("person_id",person.id);if(count.error)fail("Counting memories",count.error);const affinity=affinityFor(person,count.count||1),affinityUpdate=await db.from("people").update({computed_affinity:affinity.score,affinity_confidence:affinity.confidence,affinity_reasons:affinity.reasons}).eq("id",person.id);if(affinityUpdate.error)fail("Updating affinity",affinityUpdate.error);return{saved:true,person:{...person,computed_affinity:affinity.score},memory:savedMemory.data}}
async function bulkCapture(p:Payload){const lines=Array.isArray(p.lines)?p.lines:clean(p.text).split("\n"),results=[];for(const line of lines.map(clean).filter(Boolean)){try{results.push(await captureNote({text:line,source:"bulk"}))}catch(error){results.push({saved:false,raw:line,error:message(error)})}}return{processed:results.length,created_or_updated:results.filter((r:any)=>r.saved).length,results}}
async function editPerson(p:Payload){const db=getSupabaseAdmin();if(!p.person_id)throw new Error("person_id required");const patch:Record<string,unknown>={};for(const key of ["name","phone","email","instagram","instagram_followers","company","role","where_met","summary","importance","importance_reason","last_contact","affinity_override"])if(Object.prototype.hasOwnProperty.call(p,key))patch[key]=p[key]===""&&key==="affinity_override"?null:p[key];const r=await db.from("people").update(patch).eq("id",p.person_id).select().single();if(r.error)fail("Updating contact",r.error);return{person:r.data}}
async function stats(){const db=getSupabaseAdmin(),tables=["people","memories","interest_evidence","connections","lists","events"],counts:Record<string,number>={};for(const table of tables){const r=await db.from(table).select("*",{count:"exact",head:true});if(r.error)fail(`Counting ${table}`,r.error);counts[table]=r.count||0}return{people:counts.people,memories:counts.memories,evidence:counts.interest_evidence,connections:counts.connections,lists:counts.lists,events:counts.events,interests:counts.interest_evidence,missing_instagram:0}}
async function listLists(){const db=getSupabaseAdmin(),lists=await db.from("lists").select("*").order("created_at",{ascending:false}),members=await db.from("list_members").select("list_id");if(lists.error)fail("Loading lists",lists.error);if(members.error)fail("Loading list members",members.error);return(lists.data||[]).map(l=>({...l,list_id:l.id,member_count:(members.data||[]).filter(m=>m.list_id===l.id).length}))}
async function createList(p:Payload){const db=getSupabaseAdmin(),row={id:id("list"),name:clean(p.name),topic:clean(p.topic),description:clean(p.description)};if(!row.name)throw new Error("List name required");const r=await db.from("lists").insert(row).select().single();if(r.error)fail("Creating list",r.error);return{...r.data,list_id:r.data.id}}
async function addToList(p:Payload){const db=getSupabaseAdmin(),r=await db.from("list_members").upsert({id:id("lm"),list_id:p.list_id,person_id:p.person_id,status:p.status||"candidate",notes:p.notes||""},{onConflict:"list_id,person_id"}).select().single();if(r.error)fail("Adding person to list",r.error);return r.data}
async function getList(p:Payload){const db=getSupabaseAdmin(),list=await db.from("lists").select("*").eq("id",p.list_id).single(),members=await db.from("list_members").select("*").eq("list_id",p.list_id);if(list.error)fail("Loading list",list.error);if(members.error)fail("Loading list members",members.error);const ids=(members.data||[]).map(x=>x.person_id),people=ids.length?await db.from("people").select("*").in("id",ids):{data:[],error:null};if(people.error)fail("Loading listed people",people.error);const index=new Map((people.data||[]).map(x=>[x.id,x]));return{list:{...list.data,list_id:list.data.id},members:(members.data||[]).map(m=>({...m,contact:index.get(m.person_id)?shape(index.get(m.person_id)):null})),recommendations:[]}}
async function topicScores(p:Payload){const db=getSupabaseAdmin(),r=await db.from("topic_scores").select("*").eq("person_id",p.person_id).order("score",{ascending:false});if(r.error)fail("Loading topic scores",r.error);return r.data||[]}
async function handle(action:string,p:Payload){switch(action){case"list_people":return listPeople(p);case"search_network":return searchNetwork(p);case"get_person":return getPerson(p);case"capture_note":return captureNote(p);case"bulk_capture":return bulkCapture(p);case"edit_person":return editPerson(p);case"quick_add":return p.kind==="memory"?captureNote({text:p.value,source:"quick_add"}):editPerson(p);case"stats":return stats();case"list_lists":return listLists();case"create_list":return createList(p);case"add_to_list":return addToList(p);case"get_list":return getList(p);case"topic_scores":return topicScores(p);case"set_affinity":return editPerson({...p,affinity_override:p.affinity_score});case"clear_affinity_override":return editPerson({...p,affinity_override:null});default:throw new Error(`Supabase action not implemented yet: ${action}`)}}
export async function POST(request:NextRequest){try{const body=await request.json(),action=clean(body.action),data=await handle(action,body.payload||{});return NextResponse.json({ok:true,action,backend:"supabase",data},{headers:{"Cache-Control":"private, no-store","X-CRM-Backend":"supabase"}})}catch(error){return NextResponse.json({ok:false,backend:"supabase",error:message(error)},{status:500})}}
