/** Network OS backend v0.3 — Google Apps Script + Sheets. */
const CRM_VERSION='2026-08-04-v0.3-affinity';
const SHEETS={PEOPLE:'People',MEMORIES:'Memories',SIGNALS:'Signals',FOLLOWUPS:'FollowUps',OPPORTUNITIES:'Opportunities',CONNECTIONS:'Connections',LISTS:'Lists',LIST_MEMBERS:'ListMembers',EVENTS:'Events',EVENT_FEEDBACK:'EventFeedback',SETTINGS:'Settings'};
const HEADERS={
 People:['person_id','name','phone','email','instagram','company','role','where_met','summary','importance','importance_reason','last_contact','created_at','affinity_score'],
 Memories:['memory_id','person_id','date','raw_note','topics','event','source'],
 Signals:['signal_id','person_id','topic','signal_type','strength','confidence','evidence','source_memory_id','created_at'],
 FollowUps:['followup_id','person_id','task','due_date','status','notes'],
 Opportunities:['opportunity_id','person_id','title','type','stage','next_action','due_date','estimated_value','notes'],
 Connections:['connection_id','person_a_id','person_b_id','relationship','strength','notes','created_at'],
 Lists:['list_id','name','topic','description','created_at'],
 ListMembers:['list_member_id','list_id','person_id','status','notes','created_at'],
 Events:['event_id','name','topic','date','notes','created_at'],
 EventFeedback:['feedback_id','event_id','person_id','interest_score','fit_score','energy_score','reliability_score','notes','created_at'],
 Settings:['key','value','notes']
};
function onOpen(){SpreadsheetApp.getUi().createMenu('People CRM').addItem('Initialize / Repair Sheets','initializeCrm').addItem('Generate API Key','generateApiKey').addItem('Show API Key','showApiKey').addSeparator().addItem('Reset Test Data','resetTestData').addToUi();}
function initializeCrm(){const book=SpreadsheetApp.getActiveSpreadsheet();Object.keys(HEADERS).forEach(name=>{let sh=book.getSheetByName(name);if(!sh)sh=book.insertSheet(name);const expected=HEADERS[name],last=Math.max(sh.getLastColumn(),1),current=sh.getRange(1,1,1,last).getValues()[0].map(String);expected.forEach((header,index)=>{if(current[index]!==header)sh.getRange(1,index+1).setValue(header).setFontWeight('bold');});sh.setFrozenRows(1);});SpreadsheetApp.getUi().alert('Network OS ready. '+CRM_VERSION);}
function resetTestData(){Object.keys(HEADERS).filter(x=>x!=='Settings').forEach(name=>{const sh=sheet(name);if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,sh.getLastColumn()).clearContent();});SpreadsheetApp.getUi().alert('Test data cleared.');}
function generateApiKey(){const key=Utilities.getUuid()+Utilities.getUuid().replace(/-/g,'');PropertiesService.getScriptProperties().setProperty('CRM_API_KEY',key);SpreadsheetApp.getUi().alert('API key created.');}
function showApiKey(){SpreadsheetApp.getUi().alert(PropertiesService.getScriptProperties().getProperty('CRM_API_KEY')||'No API key found.');}
function doGet(){return json({ok:true,service:'Network OS',version:CRM_VERSION});}
function doPost(e){try{const body=parseBody(e);auth(body.api_key);const p=body.payload||{};const handlers={capture_note:()=>captureNote(p),bulk_capture:()=>bulkCapture(p),search_network:()=>searchNetwork(p),list_people:()=>listPeople(p),get_person:()=>getPerson(p),quick_add:()=>quickAdd(p),set_affinity:()=>setAffinity(p),stats:()=>stats(),diagnostics:()=>diagnostics(),create_connection:()=>createConnection(p),create_list:()=>createList(p),list_lists:()=>listLists(),add_to_list:()=>addToList(p),create_event:()=>createEvent(p),list_events:()=>listEvents(),add_event_feedback:()=>addEventFeedback(p)};if(!handlers[body.action])throw new Error('Unknown action: '+body.action);return json({ok:true,action:body.action,version:CRM_VERSION,data:handlers[body.action]()});}catch(err){return json({ok:false,version:CRM_VERSION,error:String(err.message||err)});}}
function parseBody(e){if(!e||!e.postData||!e.postData.contents)throw new Error('Missing JSON body.');return JSON.parse(e.postData.contents);}
function auth(candidate){const expected=PropertiesService.getScriptProperties().getProperty('CRM_API_KEY');if(!expected)throw new Error('API key not configured.');if(candidate!==expected)throw new Error('Unauthorized.');}
function json(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON);}
function ss(){return SpreadsheetApp.getActiveSpreadsheet();}
function sheet(name){const sh=ss().getSheetByName(name);if(!sh)throw new Error('Missing sheet '+name+'. Run initializeCrm.');return sh;}
function rows(name){const values=sheet(name).getDataRange().getValues();if(values.length<2)return[];const headers=values[0].map(String);return values.slice(1).map((r,i)=>{const o={_row:i+2};headers.forEach((h,j)=>o[h]=r[j]);return o;}).filter(o=>headers.some(h=>o[h]!==''));}
function append(name,obj){const sh=sheet(name),headers=HEADERS[name],lock=LockService.getScriptLock();lock.waitLock(10000);try{sh.appendRow(headers.map(k=>sanitize(obj[k]===undefined?'':obj[k])));}finally{lock.releaseLock();}return obj;}
function updateRow(name,rowNumber,patch){const sh=sheet(name),headers=HEADERS[name],current=sh.getRange(rowNumber,1,1,headers.length).getValues()[0];headers.forEach((k,i)=>{if(Object.prototype.hasOwnProperty.call(patch,k))current[i]=sanitize(patch[k]);});sh.getRange(rowNumber,1,1,headers.length).setValues([current]);}
function sanitize(v){if(Array.isArray(v))v=v.join(', ');if(v&&typeof v==='object'&&!(v instanceof Date))v=JSON.stringify(v);if(typeof v==='string'&&/^[=+\-@]/.test(v))return "'"+v;return v;}
function id(prefix){return prefix+'_'+Utilities.getUuid();}function now(){return new Date().toISOString();}function norm(v){return String(v||'').replace(/^'/,'').trim().toLowerCase();}function digits(v){return String(v||'').replace(/\D/g,'').slice(-10);}function clean(o){const x={};Object.keys(o||{}).forEach(k=>{if(k!=='_row')x[k]=o[k];});return x;}function same(a,b){return String(a||'').trim()===String(b||'').trim();}function clamp(n,min,max){return Math.max(min,Math.min(max,Number(n)||0));}
function findPeople(p){const all=rows(SHEETS.PEOPLE);if(p.person_id)return all.filter(x=>same(x.person_id,p.person_id));const ph=digits(p.phone),ig=norm(p.instagram).replace(/^@/,''),em=norm(p.email),name=norm(p.name||p.query);if(ph){const m=all.filter(x=>digits(x.phone)===ph);if(m.length)return m;}if(ig){const m=all.filter(x=>norm(x.instagram).replace(/^@/,'')===ig);if(m.length)return m;}if(em){const m=all.filter(x=>norm(x.email)===em);if(m.length)return m;}if(name){const exact=all.filter(x=>norm(x.name)===name);if(exact.length)return exact;const partial=all.filter(x=>norm(x.name).includes(name)||name.includes(norm(x.name)));if(partial.length===1)return partial;}return[];}
function createPerson(p){return append(SHEETS.PEOPLE,{person_id:id('person'),name:p.name||'Unknown',phone:p.phone||'',email:p.email||'',instagram:p.instagram||'',company:p.company||'',role:p.role||'',where_met:p.where_met||'',summary:p.summary||'',importance:Number(p.importance||0),importance_reason:p.importance_reason||'',last_contact:p.last_contact||'',created_at:now(),affinity_score:clamp(p.affinity_score||0,0,100)});}
function upsertPerson(p){const matches=findPeople(p);if(matches.length>1)return{ambiguous:true,matches:matches.map(clean)};if(!matches.length)return{created:true,person:createPerson(p)};const row=matches[0],patch={};['name','phone','email','instagram','company','role','where_met','summary','importance','importance_reason','last_contact','affinity_score'].forEach(k=>{if(p[k]!==undefined&&p[k]!=='')patch[k]=p[k];});updateRow(SHEETS.PEOPLE,row._row,patch);return{updated:true,person:Object.assign(clean(row),patch)};}
function parseCapture(text){const lower=norm(text),pm=text.match(/(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/),ig=text.match(/@([A-Za-z0-9._]{2,30})/),em=text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);let cleaned=text.replace(pm?pm[0]:'',' ').replace(ig?ig[0]:'',' ').trim();const cue=/\b(likes?|loves?|hates?|wants?|works?|moved|is|met|plays?|enjoys?|founder|creator|important|poker|werewolf|coworking|game night)\b/i,idx=cleaned.search(cue);if(idx>0)cleaned=cleaned.slice(0,idx).trim();cleaned=cleaned.split(/[,;|\n]/)[0].trim();const name=/^[A-Za-z][A-Za-z'.-]*(?:\s+[A-Za-z][A-Za-z'.-]*){0,3}$/.test(cleaned)?cleaned:'';const catalog=['werewolf','coworking','game night','games','poker','creator','content','founder','influencer','sponsor','sponsorship','partnership','marketing','volleyball','chess','filmmaker','youtube','instagram','tiktok'];const topics=catalog.filter(t=>lower.includes(t));return{name,phone:pm?pm[0]:'',email:em?em[0]:'',instagram:ig?'@'+ig[1]:'',summary:text,last_contact:now(),topics,signals:topics.map(topic=>({topic,type:'interest',strength:strengthFor(lower,topic)}))};}
function strengthFor(lower,topic){const e=topic.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');if(new RegExp('(hates|bad at|poor fit).{0,20}'+e+'|'+e+'.{0,20}(hates|bad at|poor fit)','i').test(lower))return 1;if(new RegExp('(obsessed|favorite|really loves|excellent at|great fit).{0,20}'+e+'|'+e+'.{0,20}(obsessed|favorite|really loves|excellent|great fit)','i').test(lower))return 5;if(new RegExp('(loves|really likes|plays every week).{0,20}'+e+'|'+e+'.{0,20}(loves|really likes|every week)','i').test(lower))return 4;if(new RegExp('(likes|enjoys|plays|wants).{0,18}'+e+'|'+e+'.{0,18}(likes|enjoys|plays|wants)','i').test(lower))return 3;return 2;}
function captureNote(p){const raw=String(p.text||p.raw_note||'').trim();if(!raw)throw new Error('Text required.');const parsed=parseCapture(raw),result=upsertPerson(parsed);if(result.ambiguous)return{saved:false,ambiguous:true,matches:result.matches};const person=result.person,memory=append(SHEETS.MEMORIES,{memory_id:id('memory'),person_id:person.person_id,date:now(),raw_note:raw,topics:parsed.topics.join(', '),event:'',source:p.source||'capture'});parsed.signals.forEach(s=>append(SHEETS.SIGNALS,{signal_id:id('signal'),person_id:person.person_id,topic:s.topic,signal_type:s.type,strength:s.strength,confidence:'rule-based',evidence:raw,source_memory_id:memory.memory_id,created_at:now()}));return{saved:true,person,memory,signals:parsed.signals};}
function bulkCapture(p){const lines=Array.isArray(p.lines)?p.lines:String(p.text||'').split('\n'),out=[];lines.map(x=>String(x).trim()).filter(Boolean).forEach(line=>{try{out.push(captureNote({text:line,source:'bulk'}));}catch(e){out.push({saved:false,error:String(e.message||e),raw:line});}});return{processed:out.length,created_or_updated:out.filter(x=>x.saved).length,results:out};}
function aggregateSignals(pid){const grouped={};rows(SHEETS.SIGNALS).filter(s=>same(s.person_id,pid)).forEach(s=>{const key=norm(s.topic);if(!key)return;if(!grouped[key])grouped[key]={topic:s.topic,strength:0,count:0,evidence:[]};grouped[key].strength=Math.max(grouped[key].strength,Number(s.strength||0));grouped[key].count++;if(s.evidence)grouped[key].evidence.push(String(s.evidence));});return Object.keys(grouped).map(k=>grouped[k]).sort((a,b)=>b.strength-a.strength);}
function enrichPerson(person){const pid=String(person.person_id||''),mem=rows(SHEETS.MEMORIES).filter(x=>same(x.person_id,pid)),signals=aggregateSignals(pid),connections=rows(SHEETS.CONNECTIONS).filter(x=>same(x.person_a_id,pid)||same(x.person_b_id,pid)),affinity=clamp(person.affinity_score||0,0,100);return{person:clean(person),affinity_score:affinity,relationship_score:affinity,interests:signals,memories_count:mem.length,connections_count:connections.length,last_memory:mem.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0))[0]||null};}
function listPeople(p){const q=norm(p.query),all=rows(SHEETS.PEOPLE).map(enrichPerson),filtered=q?all.filter(x=>norm([x.person.name,x.person.instagram,x.person.phone,x.person.summary,x.interests.map(i=>i.topic).join(' ')].join(' ')).includes(q)):all;return filtered.sort((a,b)=>b.affinity_score-a.affinity_score||b.memories_count-a.memories_count).slice(0,Number(p.limit||500));}
function searchNetwork(p){const q=norm(p.query);if(!q)throw new Error('Query required.');const terms=q.split(/\s+/).filter(Boolean),people=rows(SHEETS.PEOPLE),memories=rows(SHEETS.MEMORIES),signals=rows(SHEETS.SIGNALS);return people.map(person=>{const pid=String(person.person_id||''),pm=memories.filter(x=>same(x.person_id,pid)),ps=signals.filter(x=>same(x.person_id,pid)),text=norm([person.name,person.phone,person.email,person.instagram,person.company,person.role,person.where_met,person.summary,pm.map(x=>x.raw_note+' '+x.topics).join(' '),ps.map(x=>x.topic+' '+x.evidence).join(' ')].join(' ')),matches=terms.filter(t=>text.includes(t));if(!matches.length)return null;let score=matches.length*10;const reasons=[];ps.forEach(s=>{if(terms.some(t=>norm(s.topic).includes(t))){score+=Number(s.strength||0)*8;reasons.push(String(s.evidence||s.topic));}});if(norm(person.name).includes(q)){score+=50;reasons.unshift('Name match');}const enriched=enrichPerson(person);return{score,person:enriched.person,reasons:[...new Set(reasons)].slice(0,3),matching_memories:pm.filter(x=>terms.some(t=>norm(x.raw_note+' '+x.topics).includes(t))).map(clean),affinity_score:enriched.affinity_score,relationship_score:enriched.affinity_score,interests:enriched.interests};}).filter(Boolean).sort((a,b)=>b.score-a.score||b.affinity_score-a.affinity_score).slice(0,Number(p.limit||100));}
function getPerson(p){const matches=findPeople(p);if(matches.length!==1)return{matches:matches.map(clean)};const person=matches[0],pid=String(person.person_id),memories=rows(SHEETS.MEMORIES).filter(x=>same(x.person_id,pid)).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)),connections=rows(SHEETS.CONNECTIONS).filter(x=>same(x.person_a_id,pid)||same(x.person_b_id,pid)),index={};rows(SHEETS.PEOPLE).forEach(x=>index[x.person_id]=clean(x));return{...enrichPerson(person),memories:memories.map(clean),connections:connections.map(c=>({...clean(c),other_person:index[same(c.person_a_id,pid)?c.person_b_id:c.person_a_id]||{}}))};}
function quickAdd(p){if(!p.person_id)throw new Error('person_id required');if(p.kind==='memory')return append(SHEETS.MEMORIES,{memory_id:id('memory'),person_id:p.person_id,date:now(),raw_note:p.value||'',topics:'',event:'',source:'quick add'});if(p.kind==='interest')return append(SHEETS.SIGNALS,{signal_id:id('signal'),person_id:p.person_id,topic:p.topic||p.value,signal_type:'interest',strength:clamp(p.strength||3,1,5),confidence:'manual',evidence:p.notes||'',source_memory_id:'',created_at:now()});if(p.kind==='contact'){const row=rows(SHEETS.PEOPLE).find(x=>same(x.person_id,p.person_id));if(!row)throw new Error('Person not found');const patch={};if(p.phone)patch.phone=p.phone;if(p.instagram)patch.instagram=p.instagram;if(p.email)patch.email=p.email;updateRow(SHEETS.PEOPLE,row._row,patch);return patch;}throw new Error('Unknown quick add kind');}
function setAffinity(p){if(!p.person_id)throw new Error('person_id required');const row=rows(SHEETS.PEOPLE).find(x=>same(x.person_id,p.person_id));if(!row)throw new Error('Person not found');const score=Math.round(clamp(p.affinity_score,0,100));updateRow(SHEETS.PEOPLE,row._row,{affinity_score:score});return{person_id:p.person_id,affinity_score:score};}
function createConnection(p){const a=findPeople({person_id:p.person_a_id,name:p.person_a_name})[0],b=findPeople({person_id:p.person_b_id,name:p.person_b_name})[0];if(!a||!b)throw new Error('Both people must exist.');return append(SHEETS.CONNECTIONS,{connection_id:id('connection'),person_a_id:a.person_id,person_b_id:b.person_id,relationship:p.relationship||'Connected',strength:clamp(p.strength||3,1,5),notes:p.notes||'',created_at:now()});}
function createList(p){if(!p.name)throw new Error('List name required');return append(SHEETS.LISTS,{list_id:id('list'),name:p.name,topic:p.topic||'',description:p.description||'',created_at:now()});}
function listLists(){const members=rows(SHEETS.LIST_MEMBERS);return rows(SHEETS.LISTS).map(l=>({...clean(l),member_count:members.filter(m=>same(m.list_id,l.list_id)).length}));}
function addToList(p){if(!p.list_id||!p.person_id)throw new Error('list_id and person_id required');const exists=rows(SHEETS.LIST_MEMBERS).find(x=>same(x.list_id,p.list_id)&&same(x.person_id,p.person_id));if(exists)return clean(exists);return append(SHEETS.LIST_MEMBERS,{list_member_id:id('lm'),list_id:p.list_id,person_id:p.person_id,status:p.status||'candidate',notes:p.notes||'',created_at:now()});}
function createEvent(p){if(!p.name)throw new Error('Event name required');return append(SHEETS.EVENTS,{event_id:id('event'),name:p.name,topic:p.topic||'',date:p.date||'',notes:p.notes||'',created_at:now()});}
function listEvents(){return rows(SHEETS.EVENTS).map(clean).sort((a,b)=>new Date(b.date||b.created_at||0)-new Date(a.date||a.created_at||0));}
function addEventFeedback(p){if(!p.event_id||!p.person_id)throw new Error('event_id and person_id required');const feedback=append(SHEETS.EVENT_FEEDBACK,{feedback_id:id('fb'),event_id:p.event_id,person_id:p.person_id,interest_score:clamp(p.interest_score||0,0,5),fit_score:clamp(p.fit_score||0,0,5),energy_score:clamp(p.energy_score||0,0,5),reliability_score:clamp(p.reliability_score||0,0,5),notes:p.notes||'',created_at:now()});if(p.topic&&p.fit_score!==undefined)append(SHEETS.SIGNALS,{signal_id:id('signal'),person_id:p.person_id,topic:p.topic,signal_type:'event_fit',strength:clamp(p.fit_score,1,5),confidence:'event feedback',evidence:p.notes||('Event fit '+p.fit_score+'/5'),source_memory_id:'',created_at:now()});return feedback;}
function stats(){const people=rows(SHEETS.PEOPLE),memories=rows(SHEETS.MEMORIES),signals=rows(SHEETS.SIGNALS),connections=rows(SHEETS.CONNECTIONS),enriched=people.map(enrichPerson),avg=enriched.length?Math.round(enriched.reduce((sum,x)=>sum+x.affinity_score,0)/enriched.length):0,strong=enriched.filter(x=>x.affinity_score>=70).length;return{people:people.length,memories:memories.length,interests:new Set(signals.map(x=>norm(x.topic)).filter(Boolean)).size,signals:signals.length,connections:connections.length,lists:rows(SHEETS.LISTS).length,events:rows(SHEETS.EVENTS).length,average_affinity_score:avg,average_relationship_score:avg,missing_phone:people.filter(x=>!x.phone).length,missing_instagram:people.filter(x=>!x.instagram).length,strong_affinities:strong,strong_relationships:strong};}
function diagnostics(){return{version:CRM_VERSION,spreadsheet:ss().getName(),counts:stats(),sheets:Object.keys(HEADERS).map(name=>({name,rows:rows(name).length}))};}
