/** Network OS backend v0.6 — explainable affinity and topic intelligence. */
const CRM_VERSION='2026-08-04-v0.6-intelligence';
const SHEETS={PEOPLE:'People',MEMORIES:'Memories',SIGNALS:'Signals',EVIDENCE:'Evidence',FOLLOWUPS:'FollowUps',OPPORTUNITIES:'Opportunities',CONNECTIONS:'Connections',LISTS:'Lists',LIST_MEMBERS:'ListMembers',EVENTS:'Events',EVENT_FEEDBACK:'EventFeedback',SETTINGS:'Settings'};
const HEADERS={
 People:['person_id','name','phone','email','instagram','company','role','where_met','summary','importance','importance_reason','last_contact','created_at','affinity_score','instagram_followers','affinity_override','computed_affinity','affinity_confidence','affinity_reasons'],
 Memories:['memory_id','person_id','date','raw_note','topics','event','source'],
 Signals:['signal_id','person_id','topic','signal_type','strength','confidence','evidence','source_memory_id','created_at'],
 Evidence:['evidence_id','person_id','topic','polarity','enthusiasm','behavior','specificity','certainty','recency','score','confidence','evidence_type','quote','source_memory_id','created_at','is_correction'],
 FollowUps:['followup_id','person_id','task','due_date','status','notes'],
 Opportunities:['opportunity_id','person_id','title','type','stage','next_action','due_date','estimated_value','notes'],
 Connections:['connection_id','person_a_id','person_b_id','relationship','strength','notes','created_at'],
 Lists:['list_id','name','topic','description','created_at'],
 ListMembers:['list_member_id','list_id','person_id','status','notes','created_at'],
 Events:['event_id','name','topic','date','notes','created_at'],
 EventFeedback:['feedback_id','event_id','person_id','interest_score','fit_score','energy_score','reliability_score','notes','created_at'],
 Settings:['key','value','notes']
};
const TOPIC_ALIASES={poker:['poker','holdem','hold’em','texas hold'],werewolf:['werewolf','mafia game'],games:['game night','board game','boardgame','games'],creator:['creator','content creator','influencer','youtube','youtuber','tiktok','instagram creator'],founder:['founder','cofounder','co-founder','entrepreneur','startup'],sponsorship:['sponsor','sponsorship','brand partnership','partnership'],marketing:['marketing','growth','brand strategy'],film:['film','filmmaker','cinema','movie'],chess:['chess'],volleyball:['volleyball'],community:['community builder','organizer','host','community']};
function onOpen(){SpreadsheetApp.getUi().createMenu('People CRM').addItem('Initialize / Repair Sheets','initializeCrm').addItem('Recalculate Intelligence','recalculateAllIntelligence').addItem('Generate API Key','generateApiKey').addItem('Show API Key','showApiKey').addSeparator().addItem('Reset Test Data','resetTestData').addToUi();}
function initializeCrm(){const book=SpreadsheetApp.getActiveSpreadsheet();Object.keys(HEADERS).forEach(name=>{let sh=book.getSheetByName(name);if(!sh)sh=book.insertSheet(name);const expected=HEADERS[name],last=Math.max(sh.getLastColumn(),1),current=sh.getRange(1,1,1,last).getValues()[0].map(String);expected.forEach(header=>{if(current.indexOf(header)<0){current.push(header);sh.getRange(1,current.length).setValue(header).setFontWeight('bold');}});sh.setFrozenRows(1);});SpreadsheetApp.getUi().alert('Network OS ready. '+CRM_VERSION);}
function resetTestData(){Object.keys(HEADERS).filter(x=>x!=='Settings').forEach(name=>{const sh=sheet(name);if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,sh.getLastColumn()).clearContent();});SpreadsheetApp.getUi().alert('Test data cleared.');}
function generateApiKey(){const key=Utilities.getUuid()+Utilities.getUuid().replace(/-/g,'');PropertiesService.getScriptProperties().setProperty('CRM_API_KEY',key);SpreadsheetApp.getUi().alert('API key created.');}
function showApiKey(){SpreadsheetApp.getUi().alert(PropertiesService.getScriptProperties().getProperty('CRM_API_KEY')||'No API key found.');}
function doGet(){return json({ok:true,service:'Network OS',version:CRM_VERSION});}
function doPost(e){try{const body=parseBody(e);auth(body.api_key);const p=body.payload||{};const handlers={capture_note:()=>captureNote(p),bulk_capture:()=>bulkCapture(p),search_network:()=>searchNetwork(p),list_people:()=>listPeople(p),get_person:()=>getPerson(p),quick_add:()=>quickAdd(p),edit_person:()=>editPerson(p),set_affinity:()=>setAffinity(p),clear_affinity_override:()=>clearAffinityOverride(p),topic_scores:()=>getTopicScores(p),find_duplicates:()=>findDuplicates(p),recommend_people:()=>recommendPeople(p),recalculate_intelligence:()=>recalculateAllIntelligence(),stats:()=>stats(),diagnostics:()=>diagnostics(),create_connection:()=>createConnection(p),create_list:()=>createList(p),list_lists:()=>listLists(),get_list:()=>getList(p),add_to_list:()=>addToList(p),create_event:()=>createEvent(p),list_events:()=>listEvents(),add_event_feedback:()=>addEventFeedback(p)};if(!handlers[body.action])throw new Error('Unknown action: '+body.action);return json({ok:true,action:body.action,version:CRM_VERSION,data:handlers[body.action]()});}catch(err){return json({ok:false,version:CRM_VERSION,error:String(err.message||err)});}}
function parseBody(e){if(!e||!e.postData||!e.postData.contents)throw new Error('Missing JSON body.');return JSON.parse(e.postData.contents);}
function auth(candidate){const expected=PropertiesService.getScriptProperties().getProperty('CRM_API_KEY');if(!expected)throw new Error('API key not configured.');if(candidate!==expected)throw new Error('Unauthorized.');}
function json(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON);}
function ss(){return SpreadsheetApp.getActiveSpreadsheet();}
function sheet(name){const sh=ss().getSheetByName(name);if(!sh)throw new Error('Missing sheet '+name+'. Run initializeCrm.');return sh;}
function actualHeaders(name){return sheet(name).getRange(1,1,1,Math.max(sheet(name).getLastColumn(),1)).getValues()[0].map(String);}
function rows(name){const values=sheet(name).getDataRange().getValues();if(values.length<2)return[];const headers=values[0].map(String);return values.slice(1).map((r,i)=>{const o={_row:i+2};headers.forEach((h,j)=>o[h]=r[j]);return o;}).filter(o=>headers.some(h=>o[h]!==''));}
function append(name,obj){const sh=sheet(name),headers=actualHeaders(name),lock=LockService.getScriptLock();lock.waitLock(10000);try{sh.appendRow(headers.map(k=>sanitize(obj[k]===undefined?'':obj[k])));}finally{lock.releaseLock();}return obj;}
function updateRow(name,rowNumber,patch){const sh=sheet(name),headers=actualHeaders(name),current=sh.getRange(rowNumber,1,1,headers.length).getValues()[0];headers.forEach((k,i)=>{if(Object.prototype.hasOwnProperty.call(patch,k))current[i]=sanitize(patch[k]);});sh.getRange(rowNumber,1,1,headers.length).setValues([current]);}
function sanitize(v){if(Array.isArray(v))v=v.join(', ');if(v&&typeof v==='object'&&!(v instanceof Date))v=JSON.stringify(v);if(typeof v==='string'&&/^[=+\-@]/.test(v))return "'"+v;return v;}
function id(prefix){return prefix+'_'+Utilities.getUuid();}function now(){return new Date().toISOString();}function norm(v){return String(v||'').replace(/^'/,'').trim().toLowerCase();}function digits(v){return String(v||'').replace(/\D/g,'').slice(-10);}function clean(o){const x={};Object.keys(o||{}).forEach(k=>{if(k!=='_row')x[k]=o[k];});return x;}function same(a,b){return String(a||'').trim()===String(b||'').trim();}function clamp(n,min,max){return Math.max(min,Math.min(max,Number(n)||0));}function round(n){return Math.round(clamp(n,0,100));}function unique(a){return [...new Set(a.filter(Boolean))];}
function findPeople(p){const all=rows(SHEETS.PEOPLE);if(p.person_id)return all.filter(x=>same(x.person_id,p.person_id));const ph=digits(p.phone),ig=norm(p.instagram).replace(/^@/,''),em=norm(p.email),name=norm(p.name||p.query);if(ph){const m=all.filter(x=>digits(x.phone)===ph);if(m.length)return m;}if(ig){const m=all.filter(x=>norm(x.instagram).replace(/^@/,'')===ig);if(m.length)return m;}if(em){const m=all.filter(x=>norm(x.email)===em);if(m.length)return m;}if(name){const exact=all.filter(x=>norm(x.name)===name);if(exact.length)return exact;const partial=all.filter(x=>norm(x.name).includes(name)||name.includes(norm(x.name)));if(partial.length===1)return partial;}return[];}
function parseFollowers(v){const text=String(v||'').replace(/,/g,' ');const patterns=[/(\d+(?:\.\d+)?)\s*([km])?\s*(?:instagram|ig)?\s*(?:followers?|following)/i,/(?:instagram|ig)[^\d]{0,20}(\d+(?:\.\d+)?)\s*([km])?/i,/(\d+(?:\.\d+)?)\s*([km])?\s*(?:on|at)\s*(?:instagram|ig)/i];for(const re of patterns){const m=text.match(re);if(m){let n=Number(m[1]),unit=String(m[2]||'').toLowerCase();if(unit==='k')n*=1000;if(unit==='m')n*=1000000;if(n>=100&&n<=1000000000)return Math.round(n);}}return 0;}
function createPerson(p){return append(SHEETS.PEOPLE,{person_id:id('person'),name:p.name||'Unknown',phone:p.phone||'',email:p.email||'',instagram:p.instagram||'',company:p.company||'',role:p.role||'',where_met:p.where_met||'',summary:p.summary||'',importance:Number(p.importance||0),importance_reason:p.importance_reason||'',last_contact:p.last_contact||'',created_at:now(),affinity_score:clamp(p.affinity_score||0,0,100),instagram_followers:parseFollowers(p.instagram_followers||p.summary||''),affinity_override:'',computed_affinity:0,affinity_confidence:0,affinity_reasons:''});}
function upsertPerson(p){const matches=findPeople(p);if(matches.length>1)return{ambiguous:true,matches:matches.map(clean)};if(!matches.length)return{created:true,person:createPerson(p)};const row=matches[0],patch={};['name','phone','email','instagram','company','role','where_met','summary','importance','importance_reason','last_contact','affinity_score','instagram_followers'].forEach(k=>{if(p[k]!==undefined&&p[k]!=='')patch[k]=k==='instagram_followers'?parseFollowers(p[k])||Number(p[k])||0:p[k];});updateRow(SHEETS.PEOPLE,row._row,patch);return{updated:true,person:Object.assign(clean(row),patch)};}
function topicsIn(text){const lower=norm(text),out=[];Object.keys(TOPIC_ALIASES).forEach(topic=>{if(TOPIC_ALIASES[topic].some(alias=>lower.indexOf(alias)>=0))out.push(topic);});return unique(out);}
function phraseValue(text,sets,otherwise){for(const row of sets){if(row.words.some(w=>text.indexOf(w)>=0))return row.value;}return otherwise;}
function extractTopicEvidence(text,topic,memoryId){const lower=norm(text),aliases=TOPIC_ALIASES[topic]||[topic],positions=aliases.map(a=>lower.indexOf(a)).filter(x=>x>=0);if(!positions.length)return null;const pos=Math.min.apply(null,positions),window=lower.slice(Math.max(0,pos-90),Math.min(lower.length,pos+130));const negative=/(hate|hates|dislike|doesn't like|does not like|not interested|poor fit|bad at|stopped|used to|no longer)/.test(window);const enthusiasm=phraseValue(window,[{words:['obsessed','favorite','passion','lives for','absolutely loves','incredible at'],value:98},{words:['really loves','loves','huge fan','very into','excellent at','great at'],value:86},{words:['really likes','strong interest','very interested','enjoys a lot'],value:72},{words:['likes','enjoys','interested in','into '],value:56},{words:['might enjoy','curious','wants to learn','open to'],value:38}],28);const behavior=phraseValue(window,[{words:['plays every','weekly','every week','hosts','hosted','tournament','competes','competitive','teaches','runs a'],value:96},{words:['plays often','regularly','attended multiple','comes to every','asked to be invited'],value:82},{words:['played','attended','joined','participated'],value:58},{words:['wants to try','wants to learn'],value:34}],20);const specificity=Math.min(100,35+(window.match(/\b(weekly|monthly|hosted|tournament|beginner|competitive|regularly|every|twice|three times|last night|last month)\b/g)||[]).length*18);const certainty=/(maybe|might|possibly|i think|probably|seems)/.test(window)?48:/(definitely|clearly|always|every|regularly|obsessed|favorite)/.test(window)?94:76;const polarity=negative?-1:1;const raw=(enthusiasm*.34+behavior*.34+specificity*.16+certainty*.16)*polarity;const score=round(negative?Math.max(0,25+raw*.35):raw);const type=behavior>=80?'demonstrated_behavior':enthusiasm>=80?'strong_enthusiasm':behavior>=50?'participation':enthusiasm>=45?'stated_interest':'mention';return{evidence_id:id('ev'),topic,polarity,enthusiasm,behavior,specificity,certainty,recency:100,score,confidence:round(certainty*.55+specificity*.2+Math.max(enthusiasm,behavior)*.25),evidence_type:type,quote:String(text).slice(0,500),source_memory_id:memoryId||'',created_at:now(),is_correction:false};}
function parseCapture(text){const lower=norm(text),pm=text.match(/(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/),ig=text.match(/@([A-Za-z0-9._]{2,30})/),em=text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);let cleaned=text.replace(pm?pm[0]:'',' ').replace(ig?ig[0]:'',' ').trim();const cue=/\b(likes?|loves?|hates?|wants?|works?|moved|is|met|plays?|enjoys?|founder|creator|important|poker|werewolf|coworking|game night)\b/i,idx=cleaned.search(cue);if(idx>0)cleaned=cleaned.slice(0,idx).trim();cleaned=cleaned.split(/[,;|\n]/)[0].trim();const name=/^[A-Za-z][A-Za-z'.-]*(?:\s+[A-Za-z][A-Za-z'.-]*){0,3}$/.test(cleaned)?cleaned:'';const topics=topicsIn(lower);return{name,phone:pm?pm[0]:'',email:em?em[0]:'',instagram:ig?'@'+ig[1]:'',instagram_followers:parseFollowers(text),summary:text,last_contact:now(),topics};}
function captureNote(p){const raw=String(p.text||p.raw_note||'').trim();if(!raw)throw new Error('Text required.');const parsed=parseCapture(raw),result=upsertPerson(parsed);if(result.ambiguous)return{saved:false,ambiguous:true,matches:result.matches};const person=result.person,memory=append(SHEETS.MEMORIES,{memory_id:id('memory'),person_id:person.person_id,date:now(),raw_note:raw,topics:parsed.topics.join(', '),event:'',source:p.source||'capture'}),evidence=[];parsed.topics.forEach(topic=>{const ev=extractTopicEvidence(raw,topic,memory.memory_id);if(ev){ev.person_id=person.person_id;append(SHEETS.EVIDENCE,ev);evidence.push(ev);append(SHEETS.SIGNALS,{signal_id:id('signal'),person_id:person.person_id,topic,signal_type:ev.evidence_type,strength:Math.max(1,Math.min(5,Math.round(ev.score/20))),confidence:ev.confidence,evidence:raw,source_memory_id:memory.memory_id,created_at:now()});}});const intelligence=recalculatePersonIntelligence(person.person_id);return{saved:true,person:Object.assign(person,{instagram_followers:parsed.instagram_followers||person.instagram_followers}),memory,evidence,intelligence};}
function bulkCapture(p){const lines=Array.isArray(p.lines)?p.lines:String(p.text||'').split('\n'),out=[];lines.map(x=>String(x).trim()).filter(Boolean).forEach(line=>{try{out.push(captureNote({text:line,source:'bulk'}));}catch(e){out.push({saved:false,error:String(e.message||e),raw:line});}});return{processed:out.length,created_or_updated:out.filter(x=>x.saved).length,results:out};}
function recencyWeight(date){const age=(Date.now()-new Date(date||0).getTime())/86400000;if(!isFinite(age)||age<0)return 1;if(age<=90)return 1;if(age<=365)return .9;if(age<=730)return .72;return .55;}
function topicScoreFromRows(topic,evidenceRows,signalRows){const key=norm(topic),ev=evidenceRows.filter(x=>norm(x.topic)===key),fallback=signalRows.filter(x=>norm(x.topic)===key);if(!ev.length&&!fallback.length)return{topic,score:0,confidence:0,evidence_count:0,reasons:[]};let weighted=0,weight=0,reasons=[];ev.forEach(x=>{const rw=recencyWeight(x.created_at),confidence=clamp(x.confidence,20,100)/100,w=rw*confidence*(x.is_correction?1.8:1);weighted+=Number(x.score||0)*w;weight+=w;reasons.push({score:Number(x.score||0),text:String(x.quote||''),type:x.evidence_type,confidence:Number(x.confidence||0)});});fallback.forEach(x=>{const w=.35*recencyWeight(x.created_at);weighted+=clamp(Number(x.strength||0)*20,0,100)*w;weight+=w;});let score=weight?weighted/weight:0;const positiveCount=ev.filter(x=>Number(x.polarity||1)>0).length;score+=Math.min(10,Math.max(0,positiveCount-1)*3);const negative=ev.filter(x=>Number(x.polarity)<0);if(negative.length)score-=Math.min(35,negative.length*12);const confidence=round(Math.min(100,35+ev.length*14+fallback.length*5));return{topic,score:round(score),confidence,evidence_count:ev.length+fallback.length,reasons:reasons.sort((a,b)=>b.score-a.score).slice(0,4)};}
function personTopicScores(pid){const evidence=rows(SHEETS.EVIDENCE).filter(x=>same(x.person_id,pid)),signals=rows(SHEETS.SIGNALS).filter(x=>same(x.person_id,pid)),topics=unique(evidence.map(x=>norm(x.topic)).concat(signals.map(x=>norm(x.topic))));return topics.map(t=>topicScoreFromRows(t,evidence,signals)).sort((a,b)=>b.score-a.score);}
function computeAffinity(person,memories,connections,feedback){const text=norm([person.summary,person.importance_reason].concat(memories.map(x=>x.raw_note)).join(' '));const closeness=phraseValue(text,[{words:['best friend','closest friend','love her','love him','love them','trust completely','family to me'],value:98},{words:['close friend','good friend','really trust','amazing person','must invite'],value:84},{words:['friend','great person','like them a lot','strong relationship'],value:66},{words:['met recently','new contact','acquaintance'],value:38}],28);const enthusiasm=phraseValue(text,[{words:['absolutely amazing','incredible person','one of my favorite','so excited'],value:96},{words:['amazing','love working with','really like','great energy'],value:80},{words:['like','positive','good fit'],value:58}],35);const interaction=Math.min(100,20+memories.length*14+connections.length*8);const reliabilityRows=feedback.map(x=>Number(x.reliability_score||0)*20),reliability=reliabilityRows.length?reliabilityRows.reduce((a,b)=>a+b,0)/reliabilityRows.length:50;const alignment=/(founder|creator|organizer|community|sponsor|partner|marketing|host)/.test(text)?78:48;const strategic=Math.min(100,Number(person.importance||0)*15+(Number(person.instagram_followers||0)>=10000?20:0)+(/sponsor|partnership|collaborat|introduc|investor/.test(text)?30:0));const recency=person.last_contact?round(recencyWeight(person.last_contact)*100):45;let score=closeness*.25+enthusiasm*.20+reliability*.15+interaction*.15+alignment*.10+strategic*.10+recency*.05;const negative=(text.match(/\b(unreliable|no show|flaky|poor fit|bad energy|do not invite|avoid)\b/g)||[]).length;score-=Math.min(24,negative*8);const reasons=[];if(closeness>=75)reasons.push('Strong trust or closeness language');if(enthusiasm>=75)reasons.push('Highly positive enthusiasm in notes');if(interaction>=65)reasons.push('Repeated relationship evidence');if(reliability>=70)reasons.push('Strong event reliability');if(alignment>=70)reasons.push('Strong community or professional alignment');if(strategic>=60)reasons.push('Meaningful strategic or audience value');if(negative)reasons.push('Some negative reliability or fit evidence');const confidence=round(Math.min(100,30+memories.length*10+feedback.length*12+connections.length*6));return{score:round(score),confidence,reasons:reasons.slice(0,5),components:{closeness:round(closeness),enthusiasm:round(enthusiasm),reliability:round(reliability),interaction:round(interaction),alignment:round(alignment),strategic:round(strategic),recency:round(recency)}};}
function recalculatePersonIntelligence(pid){const person=rows(SHEETS.PEOPLE).find(x=>same(x.person_id,pid));if(!person)return null;const memories=rows(SHEETS.MEMORIES).filter(x=>same(x.person_id,pid)),connections=rows(SHEETS.CONNECTIONS).filter(x=>same(x.person_a_id,pid)||same(x.person_b_id,pid)),feedback=rows(SHEETS.EVENT_FEEDBACK).filter(x=>same(x.person_id,pid)),computed=computeAffinity(person,memories,connections,feedback),override=String(person.affinity_override||'').trim(),display=override===''?computed.score:round(override),patch={computed_affinity:computed.score,affinity_confidence:computed.confidence,affinity_reasons:computed.reasons.join(' | '),affinity_score:display};updateRow(SHEETS.PEOPLE,person._row,patch);return{person_id:pid,affinity_score:display,computed_affinity:computed.score,affinity_override:override===''?null:Number(override),confidence:computed.confidence,reasons:computed.reasons,components:computed.components,topic_scores:personTopicScores(pid)};}
function recalculateAllIntelligence(){const people=rows(SHEETS.PEOPLE),results=people.map(x=>recalculatePersonIntelligence(x.person_id));return{updated:results.length,results};}
function aggregateSignals(pid){const scores=personTopicScores(pid);return scores.map(x=>({topic:x.topic,strength:x.score/20,score:x.score,confidence:x.confidence,count:x.evidence_count,evidence:x.reasons.map(r=>r.text)}));}
function enrichPerson(person){const pid=String(person.person_id||''),mem=rows(SHEETS.MEMORIES).filter(x=>same(x.person_id,pid)),signals=aggregateSignals(pid),connections=rows(SHEETS.CONNECTIONS).filter(x=>same(x.person_a_id,pid)||same(x.person_b_id,pid)),affinity=clamp(person.affinity_score||person.computed_affinity||0,0,100);return{person:clean(person),affinity_score:affinity,computed_affinity:Number(person.computed_affinity||0),affinity_override:String(person.affinity_override||'')===''?null:Number(person.affinity_override),affinity_confidence:Number(person.affinity_confidence||0),affinity_reasons:String(person.affinity_reasons||'').split(' | ').filter(Boolean),relationship_score:affinity,interests:signals,topic_scores:signals,memories_count:mem.length,connections_count:connections.length,last_memory:mem.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0))[0]||null};}
function listPeople(p){const q=norm(p.query),all=rows(SHEETS.PEOPLE).map(enrichPerson),filtered=q?all.filter(x=>norm([x.person.name,x.person.instagram,x.person.phone,x.person.summary,x.person.role,x.person.company,x.interests.map(i=>i.topic).join(' ')].join(' ')).includes(q)):all;return filtered.sort((a,b)=>b.affinity_score-a.affinity_score||b.memories_count-a.memories_count).slice(0,Number(p.limit||500));}
function queryTopic(q){const found=topicsIn(q);return found.length?found[0]:norm(q).split(/\s+/).find(x=>x.length>2)||'';}
function searchNetwork(p){const q=norm(p.query);if(!q)throw new Error('Query required.');const terms=q.split(/\s+/).filter(Boolean),topic=queryTopic(q),people=rows(SHEETS.PEOPLE),memories=rows(SHEETS.MEMORIES);return people.map(person=>{const enriched=enrichPerson(person),pid=String(person.person_id||''),pm=memories.filter(x=>same(x.person_id,pid)),text=norm([person.name,person.phone,person.email,person.instagram,person.company,person.role,person.where_met,person.summary,pm.map(x=>x.raw_note+' '+x.topics).join(' '),enriched.interests.map(x=>x.topic).join(' ')].join(' ')),matches=terms.filter(t=>text.includes(t)||TOPIC_ALIASES[topic]&&TOPIC_ALIASES[topic].some(a=>text.includes(a)));const topicResult=enriched.interests.find(x=>norm(x.topic)===norm(topic))||{score:0,confidence:0,evidence:[]};if(!matches.length&&!topicResult.score)return null;let score=Number(topicResult.score||0)*.72+enriched.affinity_score*.18+(person.phone?5:0)+(Number(person.instagram_followers||0)>=10000?5:0);if(norm(person.name).includes(q))score+=50;return{score:round(score),topic,topic_fit:round(topicResult.score||0),topic_confidence:Number(topicResult.confidence||0),topic_reasons:(topicResult.evidence||[]).slice(0,3),person:enriched.person,reasons:(topicResult.evidence||[]).slice(0,3),matching_memories:pm.filter(x=>terms.some(t=>norm(x.raw_note+' '+x.topics).includes(t))).map(clean),affinity_score:enriched.affinity_score,computed_affinity:enriched.computed_affinity,affinity_confidence:enriched.affinity_confidence,affinity_reasons:enriched.affinity_reasons,relationship_score:enriched.affinity_score,interests:enriched.interests};}).filter(Boolean).sort((a,b)=>b.topic_fit-a.topic_fit||b.score-a.score||b.affinity_score-a.affinity_score).slice(0,Number(p.limit||100));}
function getPerson(p){const matches=findPeople(p);if(matches.length!==1)return{matches:matches.map(clean)};const person=matches[0],pid=String(person.person_id),memories=rows(SHEETS.MEMORIES).filter(x=>same(x.person_id,pid)).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)),connections=rows(SHEETS.CONNECTIONS).filter(x=>same(x.person_a_id,pid)||same(x.person_b_id,pid)),index={};rows(SHEETS.PEOPLE).forEach(x=>index[x.person_id]=clean(x));return{...enrichPerson(person),memories:memories.map(clean),connections:connections.map(c=>({...clean(c),other_person:index[same(c.person_a_id,pid)?c.person_b_id:c.person_a_id]||{}}))};}
function editPerson(p){if(!p.person_id)throw new Error('person_id required');const row=rows(SHEETS.PEOPLE).find(x=>same(x.person_id,p.person_id));if(!row)throw new Error('Person not found');const allowed=['name','phone','email','instagram','company','role','where_met','summary','importance','importance_reason','last_contact'],patch={};allowed.forEach(k=>{if(Object.prototype.hasOwnProperty.call(p,k))patch[k]=p[k];});if(Object.prototype.hasOwnProperty.call(p,'instagram_followers'))patch.instagram_followers=parseFollowers(p.instagram_followers)||Math.max(0,Number(p.instagram_followers)||0);if(Object.prototype.hasOwnProperty.call(p,'affinity_override'))patch.affinity_override=p.affinity_override===''?'':round(p.affinity_override);updateRow(SHEETS.PEOPLE,row._row,patch);return{person:Object.assign(clean(row),patch),intelligence:recalculatePersonIntelligence(p.person_id)};}
function quickAdd(p){if(!p.person_id)throw new Error('person_id required');if(p.kind==='memory')return captureNote({text:p.value||'',person_id:p.person_id,source:'quick add'});if(p.kind==='interest'){const ev={evidence_id:id('ev'),person_id:p.person_id,topic:norm(p.topic||p.value),polarity:1,enthusiasm:clamp((p.strength||3)*20,0,100),behavior:20,specificity:70,certainty:100,recency:100,score:clamp((p.strength||3)*20,0,100),confidence:100,evidence_type:'manual_interest',quote:p.notes||'',source_memory_id:'',created_at:now(),is_correction:true};append(SHEETS.EVIDENCE,ev);recalculatePersonIntelligence(p.person_id);return ev;}if(p.kind==='contact')return editPerson(p);throw new Error('Unknown quick add kind');}
function setAffinity(p){if(!p.person_id)throw new Error('person_id required');return editPerson({person_id:p.person_id,affinity_override:round(p.affinity_score)}).intelligence;}
function clearAffinityOverride(p){if(!p.person_id)throw new Error('person_id required');return editPerson({person_id:p.person_id,affinity_override:''}).intelligence;}
function getTopicScores(p){if(!p.person_id)throw new Error('person_id required');return personTopicScores(p.person_id);}
function nameSimilarity(a,b){a=norm(a).replace(/[^a-z0-9 ]/g,''),b=norm(b).replace(/[^a-z0-9 ]/g,'');if(!a||!b)return 0;if(a===b)return 1;const aa=a.split(/\s+/),bb=b.split(/\s+/),common=aa.filter(x=>bb.indexOf(x)>=0).length;return common/Math.max(aa.length,bb.length);}
function findDuplicates(p){const people=rows(SHEETS.PEOPLE),out=[];for(let i=0;i<people.length;i++)for(let j=i+1;j<people.length;j++){const a=people[i],b=people[j],reasons=[],phone=digits(a.phone)&&digits(a.phone)===digits(b.phone),email=norm(a.email)&&norm(a.email)===norm(b.email),instagram=norm(a.instagram).replace(/^@/,'')&&norm(a.instagram).replace(/^@/,'')===norm(b.instagram).replace(/^@/,''),name=nameSimilarity(a.name,b.name),company=norm(a.company)&&norm(a.company)===norm(b.company);if(phone)reasons.push('same phone');if(email)reasons.push('same email');if(instagram)reasons.push('same Instagram');if(name>=.8)reasons.push('similar name');if(company&&name>=.5)reasons.push('same company');let confidence=(phone||email||instagram)?100:name>=.9&&company?88:name>=.8?65:0;if(confidence>=Number(p.min_confidence||60))out.push({confidence,reasons,a:clean(a),b:clean(b)});}return out.sort((a,b)=>b.confidence-a.confidence).slice(0,Number(p.limit||100));}
function recommendPeople(p){const topic=norm(p.topic||p.query||''),listId=p.list_id||'',members=listId?rows(SHEETS.LIST_MEMBERS).filter(x=>same(x.list_id,listId)).map(x=>String(x.person_id)):[],people=rows(SHEETS.PEOPLE).filter(x=>members.indexOf(String(x.person_id))<0),limit=Number(p.limit||25);return people.map(person=>{const e=enrichPerson(person),fit=(e.interests.find(x=>norm(x.topic)===topic)||{score:0,confidence:0,evidence:[]}),reliability=rows(SHEETS.EVENT_FEEDBACK).filter(x=>same(x.person_id,person.person_id)).map(x=>Number(x.reliability_score||0)*20),rel=reliability.length?reliability.reduce((a,b)=>a+b,0)/reliability.length:50,reach=person.phone||person.instagram?100:20,contribution=Math.min(100,40+e.connections_count*10+(Number(person.instagram_followers||0)>=10000?15:0)),score=round(Number(fit.score||0)*.45+e.affinity_score*.25+rel*.15+reach*.05+contribution*.10),reasons=[];if(fit.score>=70)reasons.push('Strong '+topic+' interest');if(e.affinity_score>=70)reasons.push('High overall affinity');if(rel>=70)reasons.push('Reliable event history');if(person.phone)reasons.push('Reachable by phone');if(Number(person.instagram_followers||0)>=10000)reasons.push('Meaningful audience reach');return{recommendation_score:score,topic_fit:round(fit.score||0),topic_confidence:Number(fit.confidence||0),affinity_score:e.affinity_score,reliability:round(rel),reasons:reasons.slice(0,4),person:e.person};}).sort((a,b)=>b.recommendation_score-a.recommendation_score).slice(0,limit);}
function createConnection(p){const a=findPeople({person_id:p.person_a_id,name:p.person_a_name})[0],b=findPeople({person_id:p.person_b_id,name:p.person_b_name})[0];if(!a||!b)throw new Error('Both people must exist.');const result=append(SHEETS.CONNECTIONS,{connection_id:id('connection'),person_a_id:a.person_id,person_b_id:b.person_id,relationship:p.relationship||'Connected',strength:clamp(p.strength||3,1,5),notes:p.notes||'',created_at:now()});recalculatePersonIntelligence(a.person_id);recalculatePersonIntelligence(b.person_id);return result;}
function createList(p){if(!p.name)throw new Error('List name required');return append(SHEETS.LISTS,{list_id:id('list'),name:p.name,topic:p.topic||'',description:p.description||'',created_at:now()});}
function listLists(){const members=rows(SHEETS.LIST_MEMBERS);return rows(SHEETS.LISTS).map(l=>({...clean(l),member_count:members.filter(m=>same(m.list_id,l.list_id)).length}));}
function getList(p){if(!p.list_id)throw new Error('list_id required');const list=rows(SHEETS.LISTS).find(x=>same(x.list_id,p.list_id));if(!list)throw new Error('List not found');const people={};rows(SHEETS.PEOPLE).forEach(x=>people[x.person_id]=enrichPerson(x));const members=rows(SHEETS.LIST_MEMBERS).filter(x=>same(x.list_id,p.list_id)).map(x=>({...clean(x),contact:people[x.person_id]||null}));return{list:clean(list),members,recommendations:recommendPeople({list_id:p.list_id,topic:list.topic,limit:p.limit||20})};}
function addToList(p){if(!p.list_id||!p.person_id)throw new Error('list_id and person_id required');const exists=rows(SHEETS.LIST_MEMBERS).find(x=>same(x.list_id,p.list_id)&&same(x.person_id,p.person_id));if(exists)return clean(exists);return append(SHEETS.LIST_MEMBERS,{list_member_id:id('lm'),list_id:p.list_id,person_id:p.person_id,status:p.status||'candidate',notes:p.notes||'',created_at:now()});}
function createEvent(p){if(!p.name)throw new Error('Event name required');return append(SHEETS.EVENTS,{event_id:id('event'),name:p.name,topic:p.topic||'',date:p.date||'',notes:p.notes||'',created_at:now()});}
function listEvents(){return rows(SHEETS.EVENTS).map(clean).sort((a,b)=>new Date(b.date||b.created_at||0)-new Date(a.date||a.created_at||0));}
function addEventFeedback(p){if(!p.event_id||!p.person_id)throw new Error('event_id and person_id required');const feedback=append(SHEETS.EVENT_FEEDBACK,{feedback_id:id('fb'),event_id:p.event_id,person_id:p.person_id,interest_score:clamp(p.interest_score||0,0,5),fit_score:clamp(p.fit_score||0,0,5),energy_score:clamp(p.energy_score||0,0,5),reliability_score:clamp(p.reliability_score||0,0,5),notes:p.notes||'',created_at:now()});if(p.topic&&p.fit_score!==undefined){const ev={evidence_id:id('ev'),person_id:p.person_id,topic:norm(p.topic),polarity:Number(p.fit_score)>=2?1:-1,enthusiasm:clamp(Number(p.interest_score||p.fit_score)*20,0,100),behavior:100,specificity:100,certainty:100,recency:100,score:clamp(Number(p.fit_score)*20,0,100),confidence:100,evidence_type:'event_feedback',quote:p.notes||('Event fit '+p.fit_score+'/5'),source_memory_id:'',created_at:now(),is_correction:false};append(SHEETS.EVIDENCE,ev);}recalculatePersonIntelligence(p.person_id);return feedback;}
function stats(){const people=rows(SHEETS.PEOPLE),memories=rows(SHEETS.MEMORIES),signals=rows(SHEETS.SIGNALS),connections=rows(SHEETS.CONNECTIONS),enriched=people.map(enrichPerson),avg=enriched.length?Math.round(enriched.reduce((sum,x)=>sum+x.affinity_score,0)/enriched.length):0,strong=enriched.filter(x=>x.affinity_score>=70).length;return{people:people.length,memories:memories.length,interests:new Set(signals.map(x=>norm(x.topic)).filter(Boolean)).size,evidence:rows(SHEETS.EVIDENCE).length,signals:signals.length,connections:connections.length,lists:rows(SHEETS.LISTS).length,events:rows(SHEETS.EVENTS).length,average_affinity_score:avg,average_relationship_score:avg,missing_phone:people.filter(x=>!x.phone).length,missing_instagram:people.filter(x=>!x.instagram).length,strong_affinities:strong,strong_relationships:strong,possible_duplicates:findDuplicates({min_confidence:80}).length};}
function diagnostics(){return{version:CRM_VERSION,spreadsheet:ss().getName(),counts:stats(),sheets:Object.keys(HEADERS).map(name=>({name,rows:rows(name).length}))};}
